### PR TITLE
[codegen] fragment replacement results in warnings in build

### LINKED ISSUE #129: [codegen] fragment replacement results in warnings in build
```
./src/components/feed/ActorEntity.tsx
Attempted import error: 'EntityActorFragmentDoc' is not exported from './__generated/ActorEntity.graphql.ts' (imported as 'EntityActorFragmentDoc').
```

### PR DESCRIPTION
**Pull request by gabrielcsapo**
fixes #129

### CODE REVIEW

File: packages/codegen/src/babel-plugin.ts [hunk 1]
```diff
@@ -104,27 +104,40 @@ const babelPlugin = declare((api) => {
...
-          const filePath = state.filename;
-
-          if (!filePath) {
-            throw new Error('@data-eden/codegen: Unable to resolve filepath.');
-          }
+          if (operationOrFragmentName.indexOf('Fragment') > -1) {
+            // Replace the fragment with a Symbol
+            const replacementSymbol = t.callExpression(
+              t.identifier('Symbol.for'),
+              [t.stringLiteral(operationOrFragmentName)]
```
Comment (hjdivad) [inline packages/codegen/src/babel-plugin.ts:111]: let's pick some string literal so we only ever make 1 symbol rather than 1 per

`build-time-graphql-fragment` or something?

**Review by hjdivad — CHANGES_REQUESTED** [review]

File: packages/codegen/src/babel-plugin.ts (hunk 1 above)
Comment (gabrielcsapo) [reply packages/codegen/src/babel-plugin.ts:111]: that makes sense, will update.
